test: &default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID: "AYD-gy2a8cIoKyf1SU49uFsK1xDKzZTdYRdywgr_6MaZy061Q3GxyDNZHzNVfNxmNpJlkOw_75Lg81dk"
  PAYPAL_CLIENT_SECRET: "EBkm2k53dKrD77ouM4Vj0MHS23Ip-TxikZcemSKGD3rZlgLS-Vc53ejlTzdVbTf1iolTqXRKge07CPM1"
  STRIPE_PUBLISHABLE_KEY: "pk_test_51K13TVSDIvNJDEZyIIn0cQEV6TCRpKTFRl9eD6sB25CaUyUJd4OOUhv7Wde56zUlrwRZJqa3lguId62gR3lEyd3z0060JQcsA6"
  STRIPE_SECRET_KEY: "sk_test_51K13TVSDIvNJDEZyGsbLew6YFTIwgP6T6XelAlthvT2B2MpEu4yEE5T2nUQdRvdW9AUJYphcOQsHAWzwmjcElSGw00fvRp0DjT"
development:
  <<: *default